language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt 
  - pip install coveralls
  - pip3 install pytest-cov
  - pip install nose

# command to run tests 
script: 
  - python3 -m pytest --cov tests/
after_success: 
  - coveralls